"""
Run OmniCCG on every unique repository found in clone_terms_report.json.

For each unique repository:
  1. Find the earliest `created_at` date among all its MD files.
  2. Calculate days_prior = 365 + days_elapsed_since_creation
     (covers 1 year before the first MD file was added, up to today).
  3. Run:
       omniccg --git-repo https://github.com/{repo} --merge-commit true
               --days-prior {days_prior}
  4. Move generated ccg_data.xml and ccg_metrics.xml into
       results/omniccg/{owner}_{name}/
  5. Save the exact command used to command.txt in the same folder.
  6. Write a final execution_report.json with overall statistics.

Usage:
  python run_omniccg.py
"""

import json
import sys
import traceback
from datetime import datetime, timezone
from pathlib import Path

from omniccg.core import analyze_clone_genealogy

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

REPORT_PATH = Path("ai_config_results/clone_terms_report_filtered.json")
OUTPUT_ROOT = Path("results/omniccg")
FINAL_REPORT = OUTPUT_ROOT / "execution_report.json"

GITHUB_BASE = "https://github.com"
NOW = datetime.now(timezone.utc)
GENEALOGY_RESULTS = Path("genealogy_results")

# XML files generated by OmniCCG in the working directory
OMNICCG_OUTPUTS = ["ccg_data.xml", "ccg_metrics.xml"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def get_completed_from_genealogy() -> set[str]:
    """
    Scan genealogy_results/ and return a set of stems like
    '{language}_{owner}_{repo}' for repos that already have an XML file.
    """
    if not GENEALOGY_RESULTS.exists():
        return set()
    return {
        p.stem
        for p in GENEALOGY_RESULTS.glob("*.xml")
    }


def get_last_genealogy_key() -> str | None:
    """
    Find the most recently created XML file in genealogy_results/
    and return its stem (genealogy_key), e.g., 'py_user_repo'.
    Returns None if no XML files exist.
    """
    if not GENEALOGY_RESULTS.exists():
        return None
    
    xml_files = list(GENEALOGY_RESULTS.glob("*.xml"))
    if not xml_files:
        return None
    
    # Get the file with the most recent modification time
    latest_file = max(xml_files, key=lambda p: p.stat().st_mtime)
    return latest_file.stem


def find_resume_index(repos_list: list[str], last_genealogy_key: str) -> int:
    """
    Given a list of repo names and the last genealogy_key processed,
    find the index to resume from (the next unprocessed repo).
    Returns the starting index for iteration.
    """
    for i, repo_name in enumerate(repos_list):
        folder_name = repo_to_folder(repo_name)
        # Find the language for this repo to build the full genealogy_key
        # We'll check this in main and pass language info if needed
        # For now, return index of the last processed repo + 1
        if last_genealogy_key.endswith(folder_name):
            return i + 1
    return 0


def repo_to_folder(repo_name: str) -> str:
    """'apache/struts' -> 'apache_struts'"""
    return repo_name.replace("/", "_").replace(" ", "_")


def parse_date(iso: str) -> datetime | None:
    if not iso:
        return None
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00"))
    except ValueError:
        return None


def collect_repos(report_path: Path) -> dict[str, dict]:
    """
    Return a dict keyed by repo_name. Each value contains:
      - earliest_created_at (datetime)
      - nicad_language: NiCad language identifier (e.g. 'java', 'py')
      - md_files: list of file paths that matched clone terms
      - source_csvs: set of CSVs where the repo appeared
    """
    with open(report_path, encoding="utf-8") as f:
        report = json.load(f)

    repos: dict[str, dict] = {}

    for source in report.get("sources", []):
        csv_name = source.get("csv", "")
        for match in source.get("matches", []):
            repo = match["repo_name"]
            created_at = parse_date(match.get("created_at", ""))
            nicad_lang = match.get("nicad_language", "")

            if repo not in repos:
                repos[repo] = {
                    "repo_name": repo,
                    "earliest_created_at": created_at,
                    "earliest_created_at_iso": match.get("created_at", ""),
                    "nicad_language": nicad_lang,
                    "language": match.get("language", ""),
                    "md_files": [],
                    "source_csvs": set(),
                }

            entry = repos[repo]

            # Track earliest MD file creation date
            if created_at and (
                entry["earliest_created_at"] is None
                or created_at < entry["earliest_created_at"]
            ):
                entry["earliest_created_at"] = created_at
                entry["earliest_created_at_iso"] = match.get("created_at", "")

            # Keep the nicad_language if not yet set
            if not entry["nicad_language"] and nicad_lang:
                entry["nicad_language"] = nicad_lang
                entry["language"] = match.get("language", "")

            entry["md_files"].append(match["file_path"])
            entry["source_csvs"].add(csv_name)

    return repos


def build_days_list(earliest_created_at: datetime) -> list[str]:
    """
    Returns a list with 3 dates:
      1. creation_date - 1 year
      2. creation_date
      3. today
    """
    from datetime import timedelta
    return [
        (earliest_created_at - timedelta(days=365)).strftime("%Y-%m-%d"),
        earliest_created_at.strftime("%Y-%m-%d"),
        NOW.strftime("%Y-%m-%d"),
    ]


def process_repo(repo_name: str, days: list[str], nicad_language: str, output_dir: Path) -> dict:
    """
    Run the clone genealogy analysis for a single repo.

    Returns a result dict with status, command, and any error message.
    """
    git_url = f"{GITHUB_BASE}/{repo_name}"

    settings = {
        "git_repository": git_url,
        "user_settings": {
            "language": nicad_language,
            "clone_detector": "nicad",
            "days": days,
        },
        "output_path": str(output_dir),
    }

    cmd_str = (
        f"analyze_clone_genealogy(git_repository={git_url}, "
        f"language={nicad_language}, days={','.join(days)})"
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    # Save the command before running
    (output_dir / "command.txt").write_text(
        f"# OmniCCG command for {repo_name}\n"
        f"# Generated at: {NOW.isoformat()}\n"
        f"# days = creation-1year, creation, today\n\n"
        f"{cmd_str}\n",
        encoding="utf-8",
    )

    result = {
        "repo_name": repo_name,
        "command": cmd_str,
        "days": days,
        "output_dir": str(output_dir),
        "status": None,
        "return_code": None,
        "error": None,
        "files_generated": [],
    }

    try:
        genealogy_xml, lineages_xml, metrics_xml = analyze_clone_genealogy(settings)

        if lineages_xml is None and metrics_xml is None:
            result["status"] = "no_output"
            result["return_code"] = 0
        else:
            # Write output XMLs to the output directory
            if lineages_xml:
                out_file = output_dir / "ccg_data.xml"
                out_file.write_text(lineages_xml, encoding="utf-8")
                result["files_generated"].append("ccg_data.xml")
            if metrics_xml:
                out_file = output_dir / "ccg_metrics.xml"
                out_file.write_text(metrics_xml, encoding="utf-8")
                result["files_generated"].append("ccg_metrics.xml")

            result["status"] = "success"
            result["return_code"] = 0

    except ValueError as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
    except Exception as exc:
        result["status"] = "error"
        result["error"] = f"{exc}\n{traceback.format_exc()}"

    return result


def save_execution_report(
    results: list[dict],
    repos: dict[str, dict],
    report_path: Path,
) -> None:
    success  = [r for r in results if r["status"] == "success"]
    partial  = [r for r in results if r["status"] == "partial"]
    failed   = [r for r in results if r["status"] in ("failed", "error")]
    no_out   = [r for r in results if r["status"] == "no_output"]

    entries = []
    for r in results:
        repo_meta = repos.get(r["repo_name"], {})
        entries.append({
            "repo_name": r["repo_name"],
            "folder": repo_to_folder(r["repo_name"]),
            "status": r["status"],
            "return_code": r["return_code"],
            "command": r["command"],
            "output_dir": r["output_dir"],
            "files_generated": r["files_generated"],
            "days": r.get("days", ""),
            "earliest_md_created_at": repo_meta.get("earliest_created_at_iso", ""),
            "md_files_count": len(repo_meta.get("md_files", [])),
            "source_csvs": sorted(repo_meta.get("source_csvs", [])),
            "error": r.get("error"),
        })

    report = {
        "generated_at": NOW.isoformat(),
        "reference_date": NOW.strftime("%Y-%m-%d"),
        "description": (
            "OmniCCG execution summary. For each unique repository found in "
            "clone_terms_report.json, OmniCCG was run with 3 target dates: "
            "1 year before the earliest MD file creation, the creation date "
            "itself, and today."
        ),
        "tool": "omniccg",
        "output_root": str(report_path.parent),
        "days_formula": "[creation-1year, creation, today]",
        "statistics": {
            "total_repos": len(results),
            "success": len(success),
            "partial": len(partial),
            "failed": len(failed),
            "no_output": len(no_out),
        },
        "repos": entries,
    }

    report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print(f"\n[OK] Execution report saved → {report_path}")


def print_summary(results: list[dict]) -> None:
    total = len(results)
    counts = {}
    for r in results:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    print("\n" + "=" * 60)
    print(f"  OmniCCG Execution Summary  ({NOW.strftime('%Y-%m-%d')})")
    print("=" * 60)
    print(f"  Total repositories : {total}")
    for status, n in sorted(counts.items()):
        print(f"  {status:<20}: {n}")
    print("=" * 60)

    failed = [r for r in results if r["status"] not in ("success", "partial")]
    if failed:
        print("\n  Failed / problematic repos:")
        for r in failed:
            print(f"    [{r['status']}] {r['repo_name']}  — {r.get('error', '')}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not REPORT_PATH.exists():
        print(f"[ERROR] Report not found: {REPORT_PATH}", file=sys.stderr)
        sys.exit(1)

    repos = collect_repos(REPORT_PATH)
    repos_list = list(repos.keys())
    total = len(repos)
    genealogy_done = get_completed_from_genealogy()
    last_genealogy_key = get_last_genealogy_key()

    print(f"Total repositories       : {total}")
    print(f"In genealogy_results/    : {len(genealogy_done)}")
    if last_genealogy_key:
        print(f"Last genealogy generated : {last_genealogy_key}")
    print()

    # Determine resume point: skip to the repo after the last processed one
    start_index = 0
    if last_genealogy_key:
        # Find the resume point based on the last genealogy key
        for idx, repo_name in enumerate(repos_list):
            folder_name = repo_to_folder(repo_name)
            genealogy_key = f"{repos[repo_name]['nicad_language']}_{folder_name}"
            if genealogy_key == last_genealogy_key:
                start_index = idx + 1
                if start_index < total:
                    print(f"Resuming from repo #{start_index + 1}: {repos_list[start_index]}")
                else:
                    print("All repositories already processed!")
                print()
                break

    results: list[dict] = []

    for idx in range(start_index, total):
        i = idx + 1
        repo_name = repos_list[idx]
        meta = repos[repo_name]
        nicad_language = meta["nicad_language"]
        folder_name = repo_to_folder(repo_name)
        output_dir = OUTPUT_ROOT / folder_name
        genealogy_key = f"{nicad_language}_{folder_name}"

        # Resume: skip repos that already have a result in genealogy_results/
        if genealogy_key in genealogy_done:
            entry = {
                "repo_name": repo_name,
                "command": None,
                "days": None,
                "output_dir": str(output_dir),
                "status": "success",
                "return_code": 0,
                "error": None,
                "files_generated": [f"{genealogy_key}.xml"],
            }
            results.append(entry)
            print(f"[{i:3d}/{total}] {repo_name} — found in genealogy_results/, skipping.")
            continue

        if not meta["earliest_created_at"]:
            print(
                f"[{i:3d}/{total}] {repo_name}\n"
                f"          SKIPPED — no creation date available\n"
            )
            entry = {
                "repo_name": repo_name,
                "command": None,
                "days": None,
                "output_dir": str(output_dir),
                "status": "skipped",
                "return_code": None,
                "error": "no creation date",
                "files_generated": [],
            }
            results.append(entry)
            continue

        days = build_days_list(meta["earliest_created_at"])

        print(
            f"[{i:3d}/{total}] {repo_name}\n"
            f"          language            : {meta['language']} ({nicad_language})\n"
            f"          earliest_created_at : {meta['earliest_created_at_iso']}\n"
            f"          days                : {days}\n"
            f"          output_dir          : {output_dir}"
        )

        result = process_repo(repo_name, days, nicad_language, output_dir)
        results.append(result)

        status_icon = {"success": "✓", "partial": "~", "failed": "✗"}.get(
            result["status"], "!"
        )
        print(f"          status              : {status_icon} {result['status']}\n")

    save_execution_report(results, repos, FINAL_REPORT)
    print_summary(results)


if __name__ == "__main__":
    main()
