"""
Run OmniCCG on every unique repository found in clone_terms_report.json.

For each unique repository:
  1. Find the earliest `created_at` date among all its MD files.
  2. Calculate days_prior = 365 + days_elapsed_since_creation
     (covers 1 year before the first MD file was added, up to today).
  3. Run:
       omniccg --git-repo https://github.com/{repo} --merge-commit true
               --days-prior {days_prior}
  4. Move generated ccg_data.xml and ccg_metrics.xml into
       results/omniccg/{owner}_{name}/
  5. Save the exact command used to command.txt in the same folder.
  6. Write a final execution_report.json with overall statistics.

Usage:
  python run_omniccg.py
"""

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

REPORT_PATH = Path("ai_config_results/clone_terms_report_filtered.json")
OUTPUT_ROOT = Path("results/omniccg")
FINAL_REPORT = OUTPUT_ROOT / "execution_report.json"

GITHUB_BASE = "https://github.com"
NOW = datetime.now(timezone.utc)

# XML files generated by OmniCCG in the working directory
OMNICCG_OUTPUTS = ["ccg_data.xml", "ccg_metrics.xml"]

# Progress file: tracks completed repos so execution can resume
PROGRESS_FILE = OUTPUT_ROOT / "progress.json"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def repo_to_folder(repo_name: str) -> str:
    """'apache/struts' -> 'apache_struts'"""
    return repo_name.replace("/", "_").replace(" ", "_")


def parse_date(iso: str) -> datetime | None:
    if not iso:
        return None
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00"))
    except ValueError:
        return None


def collect_repos(report_path: Path) -> dict[str, dict]:
    """
    Return a dict keyed by repo_name. Each value contains:
      - earliest_created_at (datetime)
      - nicad_language: NiCad language identifier (e.g. 'java', 'py')
      - md_files: list of file paths that matched clone terms
      - source_csvs: set of CSVs where the repo appeared
    """
    with open(report_path, encoding="utf-8") as f:
        report = json.load(f)

    repos: dict[str, dict] = {}

    for source in report.get("sources", []):
        csv_name = source.get("csv", "")
        for match in source.get("matches", []):
            repo = match["repo_name"]
            created_at = parse_date(match.get("created_at", ""))
            nicad_lang = match.get("nicad_language", "")

            if repo not in repos:
                repos[repo] = {
                    "repo_name": repo,
                    "earliest_created_at": created_at,
                    "earliest_created_at_iso": match.get("created_at", ""),
                    "nicad_language": nicad_lang,
                    "language": match.get("language", ""),
                    "md_files": [],
                    "source_csvs": set(),
                }

            entry = repos[repo]

            # Track earliest MD file creation date
            if created_at and (
                entry["earliest_created_at"] is None
                or created_at < entry["earliest_created_at"]
            ):
                entry["earliest_created_at"] = created_at
                entry["earliest_created_at_iso"] = match.get("created_at", "")

            # Keep the nicad_language if not yet set
            if not entry["nicad_language"] and nicad_lang:
                entry["nicad_language"] = nicad_lang
                entry["language"] = match.get("language", "")

            entry["md_files"].append(match["file_path"])
            entry["source_csvs"].add(csv_name)

    return repos


def compute_days_prior(earliest_created_at: datetime | None) -> int:
    """
    days_prior = 365 (1 year before creation) + days elapsed since creation.
    Falls back to 730 days if date is unavailable.
    """
    if earliest_created_at is None:
        return 730  # fallback: 2 years
    days_since_creation = max((NOW - earliest_created_at).days, 0)
    return 365 + days_since_creation


def run_omniccg(repo_name: str, days_prior: int, nicad_language: str, output_dir: Path) -> dict:
    """
    Execute omniccg for the given repo. Outputs are expected in the CWD,
    so we run it in `output_dir` directly.

    Returns a result dict with status, command, and any error message.
    """
    git_url = f"{GITHUB_BASE}/{repo_name}"
    cmd = [
        "omniccg",
        "--git-repo", git_url,
        "--merge-commit", "true",
        "--days-prior", str(days_prior),
        "--language", nicad_language,
    ]
    cmd_str = " ".join(cmd)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Save the command before running
    (output_dir / "command.txt").write_text(
        f"# OmniCCG command for {repo_name}\n"
        f"# Generated at: {NOW.isoformat()}\n"
        f"# days_prior = 365 (1 year before first MD file) "
        f"+ days elapsed since creation\n\n"
        f"{cmd_str}\n",
        encoding="utf-8",
    )

    result = {
        "repo_name": repo_name,
        "command": cmd_str,
        "output_dir": str(output_dir),
        "status": None,
        "return_code": None,
        "error": None,
        "files_generated": [],
        "stdout": "",
        "stderr": "",
    }

    try:
        proc = subprocess.Popen(
            cmd,
            cwd=str(output_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        stdout_lines: list[str] = []
        for line in proc.stdout:
            print(f"          | {line}", end="")
            stdout_lines.append(line)
        proc.wait(timeout=600)

        captured = "".join(stdout_lines)
        result["return_code"] = proc.returncode
        result["stdout"] = captured.strip()[:2000]
        result["stderr"] = ""

        if proc.returncode == 0:
            # Verify expected output files exist
            generated = [
                f for f in OMNICCG_OUTPUTS
                if (output_dir / f).exists()
            ]
            result["files_generated"] = generated

            if set(generated) == set(OMNICCG_OUTPUTS):
                result["status"] = "success"
            elif generated:
                result["status"] = "partial"
            else:
                result["status"] = "no_output"
        else:
            result["status"] = "failed"
            result["error"] = f"Exit code {proc.returncode}"

    except FileNotFoundError:
        result["status"] = "tool_not_found"
        result["error"] = (
            "'omniccg' command not found. "
            "Make sure OmniCCG is installed and available in your PATH."
        )
    except subprocess.TimeoutExpired:
        result["status"] = "timeout"
        result["error"] = "OmniCCG timed out after 600 seconds."
    except Exception as exc:
        result["status"] = "error"
        result["error"] = str(exc)

    return result


def save_execution_report(
    results: list[dict],
    repos: dict[str, dict],
    report_path: Path,
) -> None:
    success  = [r for r in results if r["status"] == "success"]
    partial  = [r for r in results if r["status"] == "partial"]
    failed   = [r for r in results if r["status"] in ("failed", "error", "timeout")]
    no_out   = [r for r in results if r["status"] == "no_output"]
    not_found = [r for r in results if r["status"] == "tool_not_found"]

    entries = []
    for r in results:
        repo_meta = repos.get(r["repo_name"], {})
        entries.append({
            "repo_name": r["repo_name"],
            "folder": repo_to_folder(r["repo_name"]),
            "status": r["status"],
            "return_code": r["return_code"],
            "command": r["command"],
            "output_dir": r["output_dir"],
            "files_generated": r["files_generated"],
            "earliest_md_created_at": repo_meta.get("earliest_created_at_iso", ""),
            "days_prior_used": int(r["command"].split("--days-prior")[-1].strip())
            if "--days-prior" in r["command"] else None,
            "md_files_count": len(repo_meta.get("md_files", [])),
            "source_csvs": sorted(repo_meta.get("source_csvs", [])),
            "error": r.get("error"),
            "stderr_snippet": r.get("stderr", "")[:400] or None,
        })

    report = {
        "generated_at": NOW.isoformat(),
        "reference_date": NOW.strftime("%Y-%m-%d"),
        "description": (
            "OmniCCG execution summary. For each unique repository found in "
            "clone_terms_report.json, OmniCCG was run with days_prior = "
            "365 (one year before the earliest MD file creation) + days "
            "elapsed since that file was created. This window covers the "
            "full clone genealogy history both before and after the "
            "introduction of the agent configuration file."
        ),
        "tool": "omniccg",
        "output_root": str(report_path.parent),
        "days_prior_formula": "365 + (today - earliest_md_created_at).days",
        "statistics": {
            "total_repos": len(results),
            "success": len(success),
            "partial": len(partial),
            "failed": len(failed),
            "no_output": len(no_out),
            "tool_not_found": len(not_found),
        },
        "repos": entries,
    }

    report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print(f"\n[OK] Execution report saved → {report_path}")


def print_summary(results: list[dict]) -> None:
    total = len(results)
    counts = {}
    for r in results:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    print("\n" + "=" * 60)
    print(f"  OmniCCG Execution Summary  ({NOW.strftime('%Y-%m-%d')})")
    print("=" * 60)
    print(f"  Total repositories : {total}")
    for status, n in sorted(counts.items()):
        print(f"  {status:<20}: {n}")
    print("=" * 60)

    failed = [r for r in results if r["status"] not in ("success", "partial")]
    if failed:
        print("\n  Failed / problematic repos:")
        for r in failed:
            print(f"    [{r['status']}] {r['repo_name']}  — {r.get('error', '')}")


def is_repo_completed(repo_name: str) -> bool:
    """Check if a repo already has all expected XML output files."""
    folder = OUTPUT_ROOT / repo_to_folder(repo_name)
    return all((folder / f).exists() for f in OMNICCG_OUTPUTS)


def load_progress() -> dict:
    """Load progress state from disk."""
    if PROGRESS_FILE.exists():
        with open(PROGRESS_FILE, encoding="utf-8") as f:
            return json.load(f)
    return {"completed": [], "failed": [], "last_updated": None}


def save_progress(progress: dict) -> None:
    """Persist progress state to disk."""
    progress["last_updated"] = datetime.now(timezone.utc).isoformat()
    PROGRESS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(PROGRESS_FILE, "w", encoding="utf-8") as f:
        json.dump(progress, f, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not REPORT_PATH.exists():
        print(f"[ERROR] Report not found: {REPORT_PATH}", file=sys.stderr)
        sys.exit(1)

    repos = collect_repos(REPORT_PATH)
    total = len(repos)

    # Load progress and reconcile with actual files on disk
    progress = load_progress()
    completed_set = set(progress.get("completed", []))

    # Also check disk: if XML files exist, consider it completed
    for repo_name in repos:
        if repo_name not in completed_set and is_repo_completed(repo_name):
            completed_set.add(repo_name)

    pending = [r for r in repos if r not in completed_set]
    print(f"Total repositories : {total}")
    print(f"Already completed  : {len(completed_set)}")
    print(f"Pending            : {len(pending)}\n")

    if not pending:
        print("All repositories already processed. Nothing to do.")
        save_execution_report([], repos, FINAL_REPORT)
        return

    results: list[dict] = []

    for i, repo_name in enumerate(pending, start=1):
        meta = repos[repo_name]
        days_prior = compute_days_prior(meta["earliest_created_at"])
        folder_name = repo_to_folder(repo_name)
        output_dir = OUTPUT_ROOT / folder_name
        nicad_language = meta["nicad_language"]

        print(
            f"[{i:3d}/{len(pending)}] {repo_name}\n"
            f"          language            : {meta['language']} ({nicad_language})\n"
            f"          earliest_created_at : {meta['earliest_created_at_iso']}\n"
            f"          days_prior          : {days_prior}\n"
            f"          output_dir          : {output_dir}"
        )

        result = run_omniccg(repo_name, days_prior, nicad_language, output_dir)
        results.append(result)

        # Update progress based on actual output files
        if is_repo_completed(repo_name):
            completed_set.add(repo_name)
            result["status"] = "success"

        progress["completed"] = sorted(completed_set)
        progress["failed"] = [
            r["repo_name"] for r in results
            if r["status"] not in ("success", "partial")
        ]
        save_progress(progress)

        status_icon = {"success": "✓", "partial": "~", "failed": "✗"}.get(
            result["status"], "!"
        )
        print(f"          status              : {status_icon} {result['status']}\n")

    save_execution_report(results, repos, FINAL_REPORT)
    print_summary(results)


if __name__ == "__main__":
    main()
